'use strict';
const { ProviderAdapter, ProviderAdapterError } = require('../provider-adapter');
const normalizedStatus = (status) => status === 'live' ? 'live' : ['complete', 'completed'].includes(status) ? 'ended' : 'scheduled';
module.exports = class YouTubeAdapter extends ProviderAdapter {
    constructor({ fetch = globalThis.fetch, apiBaseUrl = 'https://www.googleapis.com/youtube/v3' } = {}) { super(); this.fetch = fetch; this.apiBaseUrl = apiBaseUrl; }
    async request(path, token) { let response; try { response = await this.fetch(`${this.apiBaseUrl}${path}`, { headers: { authorization: `Bearer ${token}` } }); } catch { throw new ProviderAdapterError('YouTube is temporarily unavailable.', 'PROVIDER_UNAVAILABLE'); } if (response.status === 401) throw new ProviderAdapterError('YouTube authorization was revoked.', 'TOKEN_REVOKED', 401); const body = await response.json().catch(() => ({})); if (!response.ok) { const reason = body.error?.errors?.[0]?.reason; if (response.status === 403 && ['insufficientPermissions', 'forbidden'].includes(reason)) throw new ProviderAdapterError('The YouTube grant is missing required scopes.', 'MISSING_SCOPES', 403); if (response.status === 403) throw new ProviderAdapterError('This channel does not have livestreaming access.', 'LIVESTREAMING_UNAVAILABLE', 403); throw new ProviderAdapterError('YouTube request failed.', 'PROVIDER_ERROR', response.status); } return body; }
    async getChannelIdentity(token) { const body = await this.request('/channels?part=id,snippet&mine=true', token); const channel = body.items?.[0]; if (!channel) throw new ProviderAdapterError('The authorized account has no YouTube channel.', 'CHANNEL_NOT_FOUND', 422); return { id: channel.id, displayName: channel.snippet?.title || channel.id, avatarUrl: channel.snippet?.thumbnails?.default?.url || null }; }
    async discoverBroadcasts(token) { const results = []; for (const status of ['active', 'upcoming']) { const body = await this.request(`/liveBroadcasts?part=id,snippet,status&mine=true&maxResults=50&broadcastStatus=${status}`, token); for (const item of body.items || []) results.push(this.normalize(item)); } return results; }
    async getBroadcast(token, id) { const body = await this.request(`/liveBroadcasts?part=id,snippet,status&id=${encodeURIComponent(id)}`, token); if (!body.items?.[0]) throw new ProviderAdapterError('The YouTube broadcast was deleted.', 'BROADCAST_DELETED', 404); return this.normalize(body.items[0]); }
    normalize(item) { return { id: item.id, title: item.snippet?.title || 'Untitled YouTube broadcast', status: normalizedStatus(item.status?.lifeCycleStatus), scheduledAt: item.snippet?.scheduledStartTime || null, startedAt: item.snippet?.actualStartTime || null, endedAt: item.snippet?.actualEndTime || null }; }
};
