'use strict';
const { ProviderAdapter, ProviderAdapterError } = require('../provider-adapter');
const normalizedStatus = (status) => status === 'live' ? 'live' : ['complete', 'completed'].includes(status) ? 'ended' : 'scheduled';
module.exports = class YouTubeAdapter extends ProviderAdapter {
    constructor({ fetch = globalThis.fetch, apiBaseUrl = 'https://www.googleapis.com/youtube/v3' } = {}) { super(); this.fetch = fetch; this.apiBaseUrl = apiBaseUrl; }
    async request(path, token, options = {}) { let response; try { response = await this.fetch(`${this.apiBaseUrl}${path}`, { method: options.method || 'GET', headers: { authorization: `Bearer ${token}`, ...(options.body && { 'content-type': 'application/json' }) }, body: options.body && JSON.stringify(options.body) }); } catch { throw Object.assign(new ProviderAdapterError('YouTube is temporarily unavailable.', 'PROVIDER_UNAVAILABLE'), { retryable: true }); } const body = await response.json().catch(() => ({})); if (!response.ok) { const reason = body.error?.errors?.[0]?.reason; const retryAfter = Number(response.headers?.get?.('retry-after')) || null; if (response.status === 401) throw Object.assign(new ProviderAdapterError('YouTube authorization expired or was revoked.', 'TOKEN_REVOKED', 401), { retryable: true }); if (response.status === 429 || reason === 'rateLimitExceeded' || reason === 'userRateLimitExceeded') throw Object.assign(new ProviderAdapterError('YouTube rate limit reached.', 'RATE_LIMITED', response.status), { retryable: true, retryAfterMs: retryAfter && retryAfter * 1000 }); if (response.status >= 500) throw Object.assign(new ProviderAdapterError('YouTube is temporarily unavailable.', 'PROVIDER_UNAVAILABLE', response.status), { retryable: true }); if (response.status === 403 && ['insufficientPermissions', 'forbidden'].includes(reason)) throw new ProviderAdapterError('The YouTube grant is missing required scopes.', 'MISSING_SCOPES', 403); if (response.status === 403) throw new ProviderAdapterError('This channel does not have livestreaming access.', 'LIVESTREAMING_UNAVAILABLE', 403); throw new ProviderAdapterError('YouTube request failed.', 'PROVIDER_ERROR', response.status); } return body; }
    async getChannelIdentity(token) { const body = await this.request('/channels?part=id,snippet&mine=true', token); const channel = body.items?.[0]; if (!channel) throw new ProviderAdapterError('The authorized account has no YouTube channel.', 'CHANNEL_NOT_FOUND', 422); return { id: channel.id, displayName: channel.snippet?.title || channel.id, avatarUrl: channel.snippet?.thumbnails?.default?.url || null }; }
    async discoverBroadcasts(token) { const results = []; for (const status of ['active', 'upcoming']) { const body = await this.request(`/liveBroadcasts?part=id,snippet,status&mine=true&maxResults=50&broadcastStatus=${status}`, token); for (const item of body.items || []) results.push(this.normalize(item)); } return results; }
    async getBroadcast(token, id) { const body = await this.request(`/liveBroadcasts?part=id,snippet,status&id=${encodeURIComponent(id)}`, token); if (!body.items?.[0]) throw new ProviderAdapterError('The YouTube broadcast was deleted.', 'BROADCAST_DELETED', 404); return this.normalize(body.items[0]); }
    async discoverLiveChat(token, broadcastId) { const body = await this.request(`/liveBroadcasts?part=id,snippet,status&id=${encodeURIComponent(broadcastId)}`, token); const item = body.items?.[0]; if (!item) throw new ProviderAdapterError('The YouTube broadcast was deleted.', 'BROADCAST_DELETED', 404); const liveChatId = item.snippet?.liveChatId; if (!liveChatId) throw new ProviderAdapterError('The broadcast has no active live chat.', 'LIVE_CHAT_UNAVAILABLE', 409); return { broadcast: this.normalize(item), liveChatId }; }
    async pollChat(token, liveChatId, pageToken) { const query = new URLSearchParams({ part: 'id,snippet,authorDetails', liveChatId, maxResults: '200' }); if (pageToken) query.set('pageToken', pageToken); const body = await this.request(`/liveChat/messages?${query}`, token); return { events: (body.items || []).map((item) => this.normalizeChat(item, liveChatId)), nextPageToken: body.nextPageToken || null, pollingIntervalMs: Math.max(1000, Number(body.pollingIntervalMillis) || 5000), offlineAt: body.offlineAt || null }; }
    normalizeChat(item, liveChatId) { const author = item.authorDetails || {}; if (!item.id || !author.channelId || !item.snippet?.displayMessage || !item.snippet?.publishedAt) throw new ProviderAdapterError('YouTube returned an invalid chat event.', 'INVALID_PROVIDER_EVENT'); return { id: item.id, sourceId: liveChatId, providerUserId: author.channelId, text: item.snippet.displayMessage, occurredAt: item.snippet.publishedAt, author: { handle: author.channelUrl?.split('/').pop() || null, displayName: author.displayName || null, avatarUrl: author.profileImageUrl || null }, relationships: [...(author.isChatModerator ? ['moderator'] : []), ...(author.isChatOwner ? ['broadcaster'] : []), ...(author.isChatSponsor ? ['paid_member'] : [])] }; }
    async sendChatMessage(token, liveChatId, text) { if (typeof text !== 'string' || !text.length || text.length > 200) throw new ProviderAdapterError('YouTube chat messages must be 1-200 characters.', 'MESSAGE_LENGTH', 422); const body = await this.request('/liveChat/messages?part=id,snippet', token, { method: 'POST', body: { snippet: { liveChatId, type: 'textMessageEvent', textMessageDetails: { messageText: text } } } }); return { id: body.id, sentAt: body.snippet?.publishedAt || new Date().toISOString() }; }
    normalize(item) { return { id: item.id, title: item.snippet?.title || 'Untitled YouTube broadcast', status: normalizedStatus(item.status?.lifeCycleStatus), scheduledAt: item.snippet?.scheduledStartTime || null, startedAt: item.snippet?.actualStartTime || null, endedAt: item.snippet?.actualEndTime || null }; }
};
